### ISSUE TITLE
Scylla MessageID missing channel 15

### ISSUE THREAD

**Issue by Jokoril** [SloneFallion/tof-boss-tracker#1]
{ key: `scyllaChannel1`, messageID: `` },
    { key: `scyllaChannel2`, messageID: `` },
    { key: `scyllaChannel3`, messageID: `` },
    { key: `scyllaChannel4`, messageID: `` },
    { key: `scyllaChannel5`, messageID: `` },
    { key: `scyllaChannel6`, messageID: `` },
    { key: `scyllaChannel7`, messageID: `` },
    { key: `scyllaChannel8`, messageID: `` },
    { key: `scyllaChannel9`, messageID: `` },
    { key: `scyllaChannel10`, messageID: `` },
    { key: `scyllaChannel11`, messageID: `` },
    { key: `scyllaChannel12`, messageID: `` },
    { key: `scyllaChannel13`, messageID: `` },
    { key: `scyllaChannel14`, messageID: `` },

---- 15 MISSING ----

    { key: `scyllaChannel16`, messageID: `` },
    { key: `scyllaChannel17`, messageID: `` },
    { key: `scyllaChannel18`, messageID: `` },
    { key: `scyllaChannel19`, messageID: `` },
    { key: `scyllaChannel20`, messageID: `` },

**Comment by SloneFallion** [comment]
This has been resolved; thank you for bringing it to my attention.
